### ISSUE TITLE
hyper v is not show in my window feture but show in system information 

### ISSUE THREAD

**Issue by MrRed369** [intel/haxm#428]
pleaser can anyone help me to solove this is problem.
 i want to disble hyper v for haxm installation 
and also i am enable the vertuallization from bios **thanku**

**Comment by wcwang** [comment]
Thanks for your questions. You may refer to this [wiki page](https://github.com/intel/haxm/wiki/Windows-Installation-Environment-Check-and-Configurations) to set up your host environment.

**Comment by wcwang** [comment]
Thanks for your questions. You may refer to this [wiki page](https://github.com/intel/haxm/wiki/Windows-Installation-Environment-Check-and-Configurations) to set up your host environment.

**Comment by MrRed369** [comment]
i have amd ryzen graphics 
is it reason perhaps?

**Comment by wcwang** [comment]
Currently HAXM only supports Intel CPU and it may be the cause of your problem if your CPU brand is AMD.

**Comment by MrRed369** [comment]
1 error


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at makeError (C:\adeshfile\adershsurf\node_modules\execa\index.js:174:9)
    at C:\adeshfile\adershsurf\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\adeshfile\adershsurf\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\adeshfile\adershsurf\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.

C:\adeshfile\adershsurf>
 I have also this error come durin make run react native app 

 at makeError (C:\adeshfile\adershsurf\node_modules\execa\index.js:174:9)
    at C:\adeshfile\adershsurf\node_modules\execa\index.js:278:16

what should i edit in this folder?
please help bro.
